workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build iOS for device
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/**/*.app
      - build/ios/**/*.ipa
      - build/ios/ipa/*.ipa
